services:
  - type: web
    name: consumet-api
    env: docker
    repo: https://github.com/shreywy/api.consumet.org.git
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: PROXY
        sync: false
      - key: TMDB_KEY
        sync: false